# We're testing on a ton of versions since this should work
# regardless of which versions of node && npm you begin with.
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
  - "iojs-v1.8.1"
